import Sidebar from "@/app/component/shared/Sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const session= await getServerSession(authOptions);
  return (
    <div className="min-h-screen">
      <div className="flex justify-between">
        <div className="w-[20%]">
          <Sidebar/>
        </div>
        <div className="w-[80%] bg-slate-100">{children}</div>
      </div>
    </div>
  );
}